### ISSUE TITLE
disk uploader task panics when secret already exists

### ISSUE THREAD

**Issue by ksimon1** [kubevirt/kubevirt-tekton-tasks#542]
**What happened**:
When user defines in Pipeline retries attribute for disk uploader task as e.g. example: 
```
    - name: upload-image-to-registries
      timeout: 9h0m0s
      retries: 2
```
the uploader task during second run panics with:

```
W1101 10:28:41.020869 18 client_config.go:659] Neither --kubeconfig nor --master was specified. Using the inClusterConfig. This might not work.
{"level":"info","ts":1730456921.0233357,"caller":"disk-uploader/main.go:39","msg":"Creating a new Secret object...","namespace":"windows-builder","name":"windows-efi-2nmxw"}
panic: secrets "windows-efi-2nmxw" already exists [recovered]
panic: secrets "windows-efi-2nmxw" already exists
goroutine 1 [running]:
github.com/kubevirt/kubevirt-tekton-tasks/modules/shared/pkg/exit.HandleExit()
/src/modules/shared/pkg/exit/exit.go:80 +0xbe
panic({0x1c7b420?, 0xc0006109e0?})
/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.6.linux-amd64/src/runtime/panic.go:770 +0x132
github.com/kubevirt/kubevirt-tekton-tasks/modules/shared/pkg/exit.ExitOrDieFromError(0x3, {0x20c3c00, 0xc0003fd360}, {0x0, 0x0, 0x11?})
/src/modules/shared/pkg/exit/exit.go:60 +0x134
main.main()
/src/cmd/disk-uploader/main.go:135 +0x385
```
**What you expected to happen**:
The task generates secret with random name

**How to reproduce it (as minimally and precisely as possible)**:
100%

/cc @codingben

**Comment by codingben** [comment]
Thanks @ksimon1 for reporting this! I'll take a look.
